# -*- coding: utf-8 -*-
"""AI投資創意競賽

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K7NaTdPJsu1vyOMVpmiq8BZfYPtVLYap
"""

# -*- coding: utf-8 -*-
"""AI投資創意競賽 — 台股加權指數 AI 預測系統 v5.0

架構：LSTM + XGBoost + RF + GB + Prophet → Stacking Meta-Learner → Regime-Aware 避險
特色：Walk-Forward 滾動訓練 / 跨市場特徵 / LLM 情緒微調 / shift(1) 防洩漏
"""

# %% [markdown]
# # AI投資創意競賽 — 台股加權指數 AI 預測系統 v5.0

# %%
# ============================================================
# CELL 0：字體（跑完後重啟 Runtime，之後跳過）
# ============================================================
!apt-get install -y fonts-noto-cjk > /dev/null 2>&1
!rm -rf ~/.cache/matplotlib
print("字體安裝完成")
print("請重啟 Runtime 後從 Cell 1 開始執行")

# %%
# ============================================================
# CELL 1：套件 + 字體
# ============================================================
!pip install yfinance prophet xgboost scikit-learn ta -q

import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm
import matplotlib.text as mtext
import seaborn as sns
import warnings, os, pickle, glob, subprocess
from datetime import datetime, timedelta

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import TimeSeriesSplit
import xgboost as xgb

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from tensorflow.keras.optimizers import Adam

from prophet import Prophet
import ta, yfinance as yf

# 字體
os.makedirs(os.path.expanduser('~/.cache/matplotlib'), exist_ok=True)
font_file = None
for lang in ['zh-tw','zh-cn','zh','ja']:
    r = subprocess.run(['fc-list',f':lang={lang}','file'], capture_output=True, text=True)
    for line in r.stdout.strip().split('\n'):
        p = line.split(':')[0].strip()
        if p and os.path.exists(p):
            font_file = p; break
    if font_file: break

FONT_PROP = None
if font_file:
    fm.fontManager.addfont(font_file)
    FONT_PROP = fm.FontProperties(fname=font_file)
    matplotlib.rcParams['font.family'] = FONT_PROP.get_name()
    print(f"字體: {FONT_PROP.get_name()}")

    _orig = mtext.Text.set_text
    def _patch(self, s):
        _orig(self, s)
        if s and any('\u4e00'<=c<='\u9fff' for c in str(s)):
            self.set_fontproperties(FONT_PROP)
    mtext.Text.set_text = _patch
    print("中文自動補丁啟用")

matplotlib.rcParams['axes.unicode_minus'] = False
plt.style.use('seaborn-v0_8-whitegrid')
warnings.filterwarnings('ignore')

fig, ax = plt.subplots(figsize=(6,0.8))
ax.text(0.5,0.5,'中文測試：台股累積報酬率 漲跌策略 買入持有',ha='center',va='center',fontsize=12)
ax.axis('off'); plt.show()
print(f"TensorFlow {tf.__version__}")

# ============================================================
# CELL 2：下載跨市場數據
# 所有外部數據 shift(1)，僅使用 T-1 日資訊，預測 T+1 日報酬
# ============================================================
USE_DRIVE = False
try:
    from google.colab import drive
    drive.mount('/content/drive', force_remount=True)
    SAVE_PATH = '/content/drive/MyDrive/AI_Investment/'
    os.makedirs(SAVE_PATH, exist_ok=True)
    USE_DRIVE = True; print("Drive OK")
except:
    SAVE_PATH = '/content/AI_Investment/'
    os.makedirs(SAVE_PATH, exist_ok=True)
print(f"路徑: {SAVE_PATH}")

print("\n下載台股...")
df = yf.download("^TWII", start="2018-01-01", end="2026-03-27", auto_adjust=True)
if isinstance(df.columns, pd.MultiIndex): df.columns = df.columns.droplevel(1)
df = df.reset_index()
df.columns = ['Date','Close','High','Low','Open','Volume']
df['Date'] = pd.to_datetime(df['Date'])
df = df.sort_values('Date').reset_index(drop=True)
print(f"  台股 {len(df)} 筆")

print("下載費半...")
sox = yf.download("^SOX", start="2018-01-01", end="2026-03-27", auto_adjust=True)
if isinstance(sox.columns, pd.MultiIndex): sox.columns = sox.columns.droplevel(1)
sox = sox.reset_index()
sox.columns = ['Date','SOX_Close','SOX_High','SOX_Low','SOX_Open','SOX_Volume']
sox['Date'] = pd.to_datetime(sox['Date'])
sox['SOX_Ret_1d'] = sox['SOX_Close'].pct_change(1)
sox['SOX_Ret_5d'] = sox['SOX_Close'].pct_change(5)
sox = sox[['Date','SOX_Close','SOX_Ret_1d','SOX_Ret_5d']]
print(f"  費半 {len(sox)} 筆")

print("下載匯率...")
twdusd = yf.download("TWD=X", start="2018-01-01", end="2026-03-27", auto_adjust=True)
if isinstance(twdusd.columns, pd.MultiIndex): twdusd.columns = twdusd.columns.droplevel(1)
twdusd = twdusd.reset_index()
twdusd.columns = ['Date','FX_Close','FX_High','FX_Low','FX_Open','FX_Volume']
twdusd['Date'] = pd.to_datetime(twdusd['Date'])
twdusd['FX_Ret_1d'] = twdusd['FX_Close'].pct_change(1)
twdusd['FX_Ret_5d'] = twdusd['FX_Close'].pct_change(5)
twdusd = twdusd[['Date','FX_Close','FX_Ret_1d','FX_Ret_5d']]
print(f"  匯率 {len(twdusd)} 筆")

# 合併（台股日期為基準）
df = df.merge(sox, on='Date', how='left')
df = df.merge(twdusd, on='Date', how='left')

# 外部數據 shift(1) 防洩漏
df['SOX_Prev_Ret']  = df['SOX_Ret_1d'].shift(1)   # 美股 T-1 日報酬
df['SOX_Prev_Ret5'] = df['SOX_Ret_5d'].shift(1)    # 美股 T-1 日 5日報酬
df['SOX_Prev_Close'] = df['SOX_Close'].shift(1)     # 美股 T-1 日收盤價
df['FX_Prev_Ret']   = df['FX_Ret_1d'].shift(1)     # 匯率 T-1 日變動
df['FX_Prev_Ret5']  = df['FX_Ret_5d'].shift(1)     # 匯率 T-1 日 5日變動

# ffill 補缺（美台休假日不同）
for c in ['SOX_Prev_Ret','SOX_Prev_Ret5','SOX_Prev_Close','FX_Prev_Ret','FX_Prev_Ret5']:
    df[c] = df[c].ffill()

print(f"\n合併完成 {len(df)} 筆 | 最新: {df['Close'].iloc[-1]:,.2f}")


# ============================================================
# CELL 3：技術指標 + 跨市場特徵
# ============================================================
print("計算特徵...")

# 台股技術指標
df['SMA_5'] = ta.trend.sma_indicator(df['Close'],5)
df['SMA_10'] = ta.trend.sma_indicator(df['Close'],10)
df['SMA_20'] = ta.trend.sma_indicator(df['Close'],20)
df['SMA_60'] = ta.trend.sma_indicator(df['Close'],60)
df['EMA_12'] = ta.trend.ema_indicator(df['Close'],12)
df['EMA_26'] = ta.trend.ema_indicator(df['Close'],26)
m = ta.trend.MACD(df['Close'])
df['MACD'] = m.macd(); df['MACD_Signal'] = m.macd_signal(); df['MACD_Hist'] = m.macd_diff()
df['RSI_14'] = ta.momentum.rsi(df['Close'],14)
df['RSI_7'] = ta.momentum.rsi(df['Close'],7)
bb = ta.volatility.BollingerBands(df['Close'],20,2)
df['BB_Width'] = bb.bollinger_wband(); df['BB_Pct'] = bb.bollinger_pband()
df['BB_Upper'] = bb.bollinger_hband(); df['BB_Lower'] = bb.bollinger_lband()
st = ta.momentum.StochasticOscillator(df['High'],df['Low'],df['Close'])
df['K'] = st.stoch(); df['D'] = st.stoch_signal()
df['ATR'] = ta.volatility.average_true_range(df['High'],df['Low'],df['Close'],14)
df['OBV'] = ta.volume.on_balance_volume(df['Close'],df['Volume'])
df['Williams_R'] = ta.momentum.williams_r(df['High'],df['Low'],df['Close'])
df['CCI'] = ta.trend.cci(df['High'],df['Low'],df['Close'])

for d in [1,2,3,5,10,20]:
    df[f'Ret_{d}d'] = df['Close'].pct_change(d)
for w in [5,10,20]:
    df[f'Vol_{w}d'] = df['Ret_1d'].rolling(w).std()

df['HL_pct'] = (df['High']-df['Low'])/df['Low']
df['CO_pct'] = (df['Close']-df['Open'])/df['Open']
df['P_SMA5'] = df['Close']/df['SMA_5']-1
df['P_SMA10'] = df['Close']/df['SMA_10']-1
df['P_SMA20'] = df['Close']/df['SMA_20']-1
df['P_SMA60'] = df['Close']/df['SMA_60']-1
df['SMA5_20'] = df['SMA_5']/df['SMA_20']-1
df['EMA12_26'] = df['EMA_12']/df['EMA_26']-1
df['MACD_n'] = df['MACD']/df['Close']
df['MACDh_n'] = df['MACD_Hist']/df['Close']
df['ATR_pct'] = df['ATR']/df['Close']
df['OBV_chg'] = df['OBV'].pct_change(5)
df['Vol_chg5'] = df['Volume'].pct_change(5)
df['Vol_ratio'] = df['Volume']/df['Volume'].rolling(20).mean()

# 跨市場特徵（已 shift(1)）
df['SOX_vs_TWII'] = df['SOX_Prev_Ret'].rolling(5).mean() - df['Ret_1d'].rolling(5).mean()


# 資金流向動能指標 (MFI)
tp = (df['High']+df['Low']+df['Close'])/3
rmf = tp*df['Volume']
pf = rmf.where(tp>tp.shift(1),0); nf = rmf.where(tp<tp.shift(1),0)
df['MFI'] = 100-(100/(1+pf.rolling(14).sum()/nf.rolling(14).sum().replace(0,1e-10)))

# 台股-費半相關性
df['TWII_SOX_corr'] = df['Ret_1d'].rolling(20).corr(df['SOX_Prev_Ret'])

# 情緒代理指標（回測用，即時部署時由 GPT 取代）
df['Sentiment_Proxy'] = (
    df['SOX_Prev_Ret'].fillna(0) * 0.6 +                    # 費半領先情緒
    df['Ret_1d'].rolling(3).mean().fillna(0) * 0.2 +         # 短期動能
    (-df['Vol_5d'].fillna(0.01) * 10 + 0.1) * 0.2            # 低波動=偏多
)

sp_max = df['Sentiment_Proxy'].abs().quantile(0.99)
if sp_max > 0:
    df['Sentiment_Proxy'] = (df['Sentiment_Proxy'] / sp_max).clip(-1, 1)


df['Sentiment_Prob'] = (df['Sentiment_Proxy'] + 1) / 2
df['Target_Ret'] = df['Close'].shift(-1)/df['Close']-1
df['Target_Dir'] = (df['Target_Ret']>0).astype(int)

df_clean = df.dropna().reset_index(drop=True)
df_clean = df_clean.replace([np.inf,-np.inf], np.nan).dropna().reset_index(drop=True)

print(f"有效資料 {len(df_clean)} 筆 | 特徵 38 個")
# %%
# ============================================================
# CELL 4：Walk-Forward 回測引擎
# ============================================================

feature_cols = [
    'Ret_1d','Ret_2d','Ret_3d','Ret_5d','Ret_10d','Ret_20d',
    'Vol_5d','Vol_10d','Vol_20d','HL_pct','CO_pct',
    'P_SMA5','P_SMA10','P_SMA20','P_SMA60','SMA5_20','EMA12_26',
    'MACD_n','MACDh_n','RSI_14','RSI_7','BB_Width','BB_Pct',
    'K','D','ATR_pct','Williams_R','CCI','OBV_chg','Vol_chg5','Vol_ratio',
    'SOX_Prev_Ret','SOX_Prev_Ret5','SOX_vs_TWII',
    'FX_Prev_Ret','FX_Prev_Ret5','MFI','TWII_SOX_corr',
]

print(f"特徵: {len(feature_cols)} 個")

test_start = '2020-07-01'
for col in feature_cols:
    df_clean[col] = df_clean[col].replace([np.inf,-np.inf], np.nan)
df_clean = df_clean.dropna(subset=feature_cols).reset_index(drop=True)
all_test = df_clean[df_clean['Date']>=test_start].copy()

print(f"  測試: {all_test['Date'].min().strftime('%Y-%m-%d')} ~ {all_test['Date'].max().strftime('%Y-%m-%d')} ({len(all_test)}天)")
print(f"  漲比例: {all_test['Target_Dir'].mean()*100:.1f}%")

wf_results = []
test_months = all_test['Date'].dt.to_period('M').unique()

for month in test_months:
    md = all_test[all_test['Date'].dt.to_period('M')==month]
    if len(md)<5: continue
    te = md['Date'].min()-timedelta(days=1)
    ts = df_clean['Date'].min()
    td = df_clean[(df_clean['Date']>=ts)&(df_clean['Date']<=te)]
    if len(td)<200: continue

    sc = StandardScaler()
    Xtr = sc.fit_transform(td[feature_cols])
    Xte = sc.transform(md[feature_cols])
    ytr_r = td['Target_Ret'].values
    ytr_d = td['Target_Dir'].values
    spw = (ytr_d==0).sum()/max((ytr_d==1).sum(),1)

    xc = xgb.XGBClassifier(n_estimators=200,max_depth=3,learning_rate=0.03,
        subsample=0.7,colsample_bytree=0.7,reg_alpha=1.0,reg_lambda=3.0,
        scale_pos_weight=spw,random_state=42,use_label_encoder=False,eval_metric='logloss')
    xc.fit(Xtr,ytr_d,verbose=0)

    xr = xgb.XGBRegressor(n_estimators=200,max_depth=3,learning_rate=0.03,
        subsample=0.7,colsample_bytree=0.7,reg_alpha=1.0,reg_lambda=3.0,random_state=42)
    xr.fit(Xtr,ytr_r,verbose=0)

    rf = RandomForestClassifier(n_estimators=300,max_depth=4,min_samples_leaf=30,
        class_weight='balanced',random_state=42)
    rf.fit(Xtr,ytr_d)

    gb = GradientBoostingClassifier(n_estimators=200,max_depth=3,learning_rate=0.05,
        subsample=0.8,random_state=42)
    gb.fit(Xtr,ytr_d)

    xp = xc.predict_proba(Xte)[:,1]
    rp = rf.predict_proba(Xte)[:,1]
    gp = gb.predict_proba(Xte)[:,1]

    for i,(_,row) in enumerate(md.iterrows()):
        wf_results.append({
            'Date':row['Date'],'Close':row['Close'],
            'Actual_Ret':row['Target_Ret'],'Actual_Dir':row['Target_Dir'],
            'XGB_prob':xp[i],'XGB_dir':int(xp[i]>0.5),
            'RF_prob':rp[i],'RF_dir':int(rp[i]>0.5),
            'GB_prob':gp[i],'GB_dir':int(gp[i]>0.5),
        })
    print(f"  {month}: {len(td)}→{len(md)} | XGB漲{(xp>0.5).sum()}/{len(xp)}")

wf_df = pd.DataFrame(wf_results)
print(f"\nWalk-Forward 完成: {len(wf_df)} 筆")
last_scaler=sc; last_xgb_cls=xc; last_xgb_reg=xr; last_rf=rf; last_gb=gb

# %%
# ============================================================
# CELL 5：LSTM 方向分類模型
# ============================================================
print("[LSTM T+1 方向預測]")

SEQ_LENGTH = 15
train_cutoff = all_test['Date'].min() - timedelta(days=1)

sc_lstm = StandardScaler()
X_lstm_all = sc_lstm.fit_transform(df_clean[feature_cols])
dirs_all = df_clean['Target_Dir'].values
n_tr = len(df_clean[df_clean['Date'] <= train_cutoff])

def make_seq(X, y, seq_len):
    Xs, Ys = [], []
    for i in range(seq_len, len(X)):
        Xs.append(X[i-seq_len:i])
        Ys.append(y[i])
    return np.array(Xs), np.array(Ys)


X_s, y_s = make_seq(X_lstm_all, dirs_all, SEQ_LENGTH)

ns = n_tr - SEQ_LENGTH
sp = int(ns * 0.85)
Xtr, ytr = X_s[:sp], y_s[:sp]
Xva, yva = X_s[sp:ns], y_s[sp:ns]
Xte = X_s[ns:]

from sklearn.utils.class_weight import compute_class_weight
cw = compute_class_weight('balanced', classes=np.array([0,1]), y=ytr.astype(int))
class_weights = {0: cw[0], 1: cw[1]}

print(f"  訓練: {Xtr.shape} | 驗證: {Xva.shape} | 測試: {Xte.shape}")
print(f"  類別權重: 跌={cw[0]:.2f} 漲={cw[1]:.2f}")

model_lstm = Sequential([
    LSTM(48, return_sequences=True, input_shape=(SEQ_LENGTH, len(feature_cols))),
    BatchNormalization(), Dropout(0.3),
    LSTM(24),
    BatchNormalization(), Dropout(0.3),
    Dense(12, activation='relu'),
    Dropout(0.2),
    Dense(1, activation='sigmoid')
])
model_lstm.compile(optimizer=Adam(0.0005),
                   loss='binary_crossentropy',
                   metrics=['accuracy'])

cb = [EarlyStopping('val_loss', patience=20, restore_best_weights=True),
      ReduceLROnPlateau('val_loss', factor=0.5, patience=7, min_lr=1e-6)]

# 用 class_weight 處理不平衡
history = model_lstm.fit(Xtr, ytr, validation_data=(Xva, yva),
                         epochs=150, batch_size=64, callbacks=cb,
                         class_weight=class_weights, verbose=1)

# 驗證集最佳門檻
val_prob = model_lstm.predict(Xva, verbose=0).flatten()
best_t, best_a = 0.5, 0
for t in np.arange(0.35, 0.65, 0.01):
    a = np.mean((val_prob > t) == yva)
    if a > best_a:
        best_t, best_a = t, a
best_t = max(best_t, 0.45)
print(f"\n  最佳門檻: {best_t:.2f} (驗證準確率: {best_a*100:.1f}%)")

# 測試集預測
lstm_prob_arr = model_lstm.predict(Xte, verbose=0).flatten()
lstm_dir_pred = (lstm_prob_arr > best_t).astype(int)

# 對齊到 wf_df
if len(lstm_prob_arr) >= len(wf_df):
    wf_df['LSTM_prob'] = lstm_prob_arr[:len(wf_df)]
    wf_df['LSTM_dir'] = lstm_dir_pred[:len(wf_df)]
else:
    wf_df['LSTM_prob'] = np.nan
    wf_df['LSTM_dir'] = np.nan
    n = len(lstm_prob_arr)
    wf_df.iloc[-n:, wf_df.columns.get_loc('LSTM_prob')] = lstm_prob_arr
    wf_df.iloc[-n:, wf_df.columns.get_loc('LSTM_dir')] = lstm_dir_pred


wf_df['LSTM_ret'] = (wf_df['LSTM_prob'] - 0.5) * 0.02  # 機率轉近似漲跌幅

wf_df = wf_df.dropna().reset_index(drop=True)

lstm_acc = (wf_df['LSTM_dir'] == wf_df['Actual_Dir']).mean()
print(f"\n  LSTM: {lstm_acc*100:.1f}%")
print(f"  漲 {wf_df['LSTM_dir'].sum()}/{len(wf_df)} ({wf_df['LSTM_dir'].mean()*100:.0f}%)")
print(f"  機率範圍: [{lstm_prob_arr.min():.3f}, {lstm_prob_arr.max():.3f}]")

# 存 lstm_models 供 Cell 9 使用（只有 T+1）
lstm_models = {1: model_lstm}
LSTM_THRESHOLD = best_t

fig, axes = plt.subplots(1, 2, figsize=(14, 4))

axes[0].plot(history.history['accuracy'], label='訓練')
axes[0].plot(history.history['val_accuracy'], label='驗證')
axes[0].set_title('LSTM 準確率'); axes[0].legend()

axes[1].plot(history.history['loss'], label='訓練')
axes[1].plot(history.history['val_loss'], label='驗證')
axes[1].set_title('LSTM 損失'); axes[1].legend()

plt.tight_layout()
plt.savefig(SAVE_PATH+'lstm_training_curve.png', dpi=150, bbox_inches='tight')
plt.show()

# %%
# ============================================================
# CELL 6：Prophet
# ============================================================
print("Prophet...")

prophet_train = pd.DataFrame({
    'ds':df_clean[df_clean['Date']<test_start]['Date'].values,
    'y':df_clean[df_clean['Date']<test_start]['Close'].values})
model_prophet = Prophet(daily_seasonality=False,weekly_seasonality=True,
    yearly_seasonality=True,changepoint_prior_scale=0.1,seasonality_mode='multiplicative')
model_prophet.add_seasonality(name='monthly',period=30.5,fourier_order=5)
model_prophet.fit(prophet_train)

pf=model_prophet.predict(pd.DataFrame({'ds':wf_df['Date'].values}))
wf_df['Prophet_price']=pf['yhat'].values
wf_df['Prophet_ret']=pf['yhat'].pct_change().fillna(0).values
wf_df['Prophet_dir']=(wf_df['Prophet_ret']>0).astype(int)
wf_df['Prophet_prob']=1/(1+np.exp(-wf_df['Prophet_ret']*100))

pa=(wf_df['Prophet_dir']==wf_df['Actual_Dir']).mean()
print(f"  Prophet: {pa*100:.1f}% | 漲 {wf_df['Prophet_dir'].sum()}/{len(wf_df)}")

fig=model_prophet.plot_components(pf)
plt.savefig(SAVE_PATH+'prophet_components.png',dpi=150,bbox_inches='tight'); plt.show()

fig,ax=plt.subplots(figsize=(14,6))
ax.plot(wf_df['Date'],wf_df['Close'],'b-',label='實際',linewidth=2)
ax.plot(wf_df['Date'],wf_df['Prophet_price'],'r--',label='Prophet',linewidth=1.5)
ax.set_title('Prophet 預測 vs 實際'); ax.legend()
plt.tight_layout(); plt.savefig(SAVE_PATH+'prophet_prediction.png',dpi=150,bbox_inches='tight'); plt.show()

# %%
# ============================================================
# CELL 7：Stacking Meta-Learner + Regime Detection + LLM 微調
# ============================================================

print("\n[Stacking Meta-Learner + Regime Switching]")

prob_cols = ['LSTM_prob','XGB_prob','RF_prob','GB_prob','Prophet_prob']

if 'Prophet_ret' in wf_df.columns:
    wf_df['Prophet_prob'] = 1/(1+np.exp(-wf_df['Prophet_ret']*100))
else:
    wf_df['Prophet_prob'] = 0.5

for c in prob_cols:
    if c not in wf_df.columns:
        wf_df[c] = 0.5

# 準確率
acc = {}
for name, dc in [('LSTM','LSTM_dir'),('XGBoost','XGB_dir'),('RF','RF_dir'),
                  ('GB','GB_dir')]:
    acc[name] = (wf_df[dc]==wf_df['Actual_Dir']).mean()
    print(f"  {name:10s}: {acc[name]*100:.1f}%  漲 {wf_df[dc].mean()*100:.0f}%")
if 'Prophet_dir' in wf_df.columns:
    acc['Prophet'] = (wf_df['Prophet_dir']==wf_df['Actual_Dir']).mean()
    print(f"  {'Prophet':10s}: {acc['Prophet']*100:.1f}%  漲 {wf_df['Prophet_dir'].mean()*100:.0f}%")

# --- Meta-Learner ---
print("\n  [Meta-Learner]")
X_meta = wf_df[prob_cols].values
y_meta = wf_df['Actual_Dir'].values

tscv = TimeSeriesSplit(n_splits=5)
ms = []
for fold, (tri, tei) in enumerate(tscv.split(X_meta)):
    tm = LogisticRegression(C=1.0, class_weight='balanced', random_state=42)
    tm.fit(X_meta[tri], y_meta[tri])
    s = tm.score(X_meta[tei], y_meta[tei]); ms.append(s)
    print(f"    Fold {fold+1}: {s*100:.1f}%")
print(f"    平均: {np.mean(ms)*100:.1f}% +/- {np.std(ms)*100:.1f}%")

si = int(len(X_meta)*0.8)
meta_model = LogisticRegression(C=1.0, class_weight='balanced', random_state=42)
meta_model.fit(X_meta[:si], y_meta[:si])

mp = meta_model.predict_proba(X_meta)[:,1]
wf_df['Meta_prob'] = mp
wf_df['Meta_dir'] = (mp > 0.5).astype(int)

meta_acc = (wf_df['Meta_dir']==wf_df['Actual_Dir']).mean()
print(f"    Meta: {meta_acc*100:.1f}%  漲 {wf_df['Meta_dir'].mean()*100:.0f}%")

coef = pd.Series(meta_model.coef_[0], index=['LSTM','XGBoost','RF','GB','Prophet'])
print(f"\n  [Meta 權重]")
for n, w in coef.sort_values(ascending=False).items():
    print(f"    {n:10s}: {w:+.3f}")

# 投票
vdc = ['LSTM_dir','XGB_dir','RF_dir','GB_dir']
if 'Prophet_dir' in wf_df.columns: vdc.append('Prophet_dir')
wf_df['Vote_sum'] = wf_df[vdc].sum(axis=1)
wf_df['Ensemble_vote'] = (wf_df['Vote_sum']>=3).astype(int)

# Market Regime 判斷
print("\n  [Market Regime Detection]")

vol_lookup = df_clean.set_index('Date')['Vol_5d'].to_dict()
ret20_lookup = df_clean.set_index('Date')['Ret_20d'].to_dict()
rsi_lookup = df_clean.set_index('Date')['RSI_14'].to_dict()

def detect_regime(date):

    vol = vol_lookup.get(date, 0.01)
    ret20 = ret20_lookup.get(date, 0.0)
    rsi = rsi_lookup.get(date, 50)

    if vol > 0.020 and ret20 < -0.05:
        return 'Crisis'
    elif vol > 0.015 and ret20 < 0:
        return 'Risk-off'
    elif ret20 > 0.05 and rsi > 60:
        return 'Bullish'
    elif ret20 < -0.02 and rsi < 40:
        return 'Bearish'
    else:
        return 'Neutral'

wf_df['Regime'] = wf_df['Date'].apply(detect_regime)

# 各 regime 統計
print(f"\n  [Regime 分布]")
for regime in ['Bullish','Neutral','Bearish','Risk-off','Crisis']:
    sub = wf_df[wf_df['Regime']==regime]
    if len(sub) > 0:
        avg_ret = sub['Actual_Ret'].mean()*100
        meta_a = (sub['Meta_dir']==sub['Actual_Dir']).mean()*100
        print(f"    {regime:10s}: {len(sub):4d}天 | 均報酬{avg_ret:+.3f}% | Meta準確{meta_a:.0f}%")

# Regime-Aware 避險
BASE_THRESHOLD = 0.55

wf_df['LongBias_Meta'] = 1
wf_df['Dynamic_Threshold'] = 0.0

for idx, row in wf_df.iterrows():
    regime = row['Regime']
    vol = vol_lookup.get(row['Date'], 0.01)

    # 根據 Regime 設定門檻
    if regime == 'Crisis':
        threshold = 0.40
    elif regime == 'Risk-off':
        threshold = 0.45
    elif regime == 'Bearish':
        threshold = 0.50
    elif regime == 'Neutral':
        threshold = BASE_THRESHOLD
    else:  # Bullish
        threshold = 0.60

    # 高波動額外加強（不管 regime）
    if vol > 0.025:
        threshold = min(threshold, 0.42)

    wf_df.at[idx, 'Dynamic_Threshold'] = threshold

    if row['Meta_prob'] < (1 - threshold):
        wf_df.at[idx, 'LongBias_Meta'] = 0

HEDGE_THRESHOLD = BASE_THRESHOLD

# --- 統計 ---
hp = wf_df['LongBias_Meta'].mean()*100
hd = wf_df[wf_df['LongBias_Meta']==0]
kd = wf_df[wf_df['LongBias_Meta']==1]

print(f"\n  [Regime-Aware 避險]")
print(f"  持有 {hp:.0f}% | 避險 {100-hp:.0f}%")
if len(hd) > 0:
    print(f"  避險日均報酬: {hd['Actual_Ret'].mean()*100:+.3f}% ({len(hd)}天)")
print(f"  持有日均報酬: {kd['Actual_Ret'].mean()*100:+.3f}% ({len(kd)}天)")

# 各 regime 下的避險效果
print(f"\n  [各 Regime 避險比例]")
for regime in ['Bullish','Neutral','Bearish','Risk-off','Crisis']:
    sub = wf_df[wf_df['Regime']==regime]
    if len(sub) > 0:
        h_pct = (1-sub['LongBias_Meta'].mean())*100
        print(f"    {regime:10s}: 避險{h_pct:4.0f}% | 天數{len(sub)}")

print(f"\n  [投票分布]")
for v in range(6):
    ct = (wf_df['Vote_sum']==v).sum()
    if ct > 0:
        sb = wf_df[wf_df['Vote_sum']==v]
        print(f"    {v}/5看漲: {ct:3d}天 | 實際漲{sb['Actual_Dir'].mean()*100:.0f}% | 均報酬{sb['Actual_Ret'].mean()*100:+.2f}%")
# LLM 機率微調器
print(f"\n  [LLM 機率微調器]")

ALPHA = 0.10

# 從 df_clean 取情緒代理
sent_lookup = df_clean.set_index('Date')['Sentiment_Proxy'].to_dict()
wf_df['Sent_Score'] = wf_df['Date'].map(sent_lookup).fillna(0)  # [-1, 1]

wf_df['Adjusted_Prob'] = wf_df['Meta_prob'] * (1 + ALPHA * wf_df['Sent_Score'])
wf_df['Adjusted_Prob'] = wf_df['Adjusted_Prob'].clip(0, 1)
wf_df['Adjusted_dir'] = (wf_df['Adjusted_Prob'] > 0.5).astype(int)

# Adjusted + Regime-Aware 避險
wf_df['LongBias_Adjusted'] = 1
for idx, row in wf_df.iterrows():
    regime = row['Regime']
    if regime == 'Crisis': t = 0.40
    elif regime == 'Risk-off': t = 0.45
    elif regime == 'Bearish': t = 0.50
    elif regime == 'Neutral': t = BASE_THRESHOLD
    else: t = 0.60

    vol = vol_lookup.get(row['Date'], 0.01)
    if vol > 0.025: t = min(t, 0.42)

    if row['Adjusted_Prob'] < (1 - t):
        wf_df.at[idx, 'LongBias_Adjusted'] = 0

adj_acc = (wf_df['Adjusted_dir']==wf_df['Actual_Dir']).mean()
adj_hold = wf_df['LongBias_Adjusted'].mean()*100

print(f"  alpha = {ALPHA}")
print(f"  公式: Final_Prob = Meta_Prob * (1 + {ALPHA} * LLM_score)")
print(f"  Adjusted 準確率: {adj_acc*100:.1f}%")
print(f"  Adjusted 濾網: 持有{adj_hold:.0f}% / 避險{100-adj_hold:.0f}%")

# 診斷：LLM 調整了多少
diff = (wf_df['Adjusted_Prob'] - wf_df['Meta_prob']).abs()
print(f"  平均調整幅度: {diff.mean()*100:.2f}% (最大{diff.max()*100:.2f}%)")

# 調整效果：LLM 看空時避險日的報酬
sent_neg = wf_df[wf_df['Sent_Score'] < -0.1]
sent_pos = wf_df[wf_df['Sent_Score'] > 0.1]
if len(sent_neg) > 0:
    print(f"  LLM偏空日({len(sent_neg)}天) 實際均報酬: {sent_neg['Actual_Ret'].mean()*100:+.3f}%")
if len(sent_pos) > 0:
    print(f"  LLM偏多日({len(sent_pos)}天) 實際均報酬: {sent_pos['Actual_Ret'].mean()*100:+.3f}%")

# 舊版融合（做對比用）
wf_df['Fusion_Prob'] = wf_df['Meta_prob'] * 0.7 + ((wf_df['Sent_Score']+1)/2) * 0.3
wf_df['LongBias_Fusion'] = 1
for idx, row in wf_df.iterrows():
    regime = row['Regime']
    if regime == 'Crisis': t = 0.40
    elif regime == 'Risk-off': t = 0.45
    elif regime == 'Bearish': t = 0.50
    elif regime == 'Neutral': t = BASE_THRESHOLD
    else: t = 0.60
    vol = vol_lookup.get(row['Date'], 0.01)
    if vol > 0.025: t = min(t, 0.42)
    if row['Fusion_Prob'] < (1 - t):
        wf_df.at[idx, 'LongBias_Fusion'] = 0

# %%
# ============================================================
# CELL 8：回測績效
# ============================================================
print("回測...")

ar=wf_df['Actual_Ret'].values
def sr(p,a): return np.array([a[i] if p[i]==1 else 0 for i in range(len(p))])

strats={
    'LSTM':sr(wf_df['LSTM_dir'].values,ar),
    'XGBoost':sr(wf_df['XGB_dir'].values,ar),
    'RF':sr(wf_df['RF_dir'].values,ar),
    'GB':sr(wf_df['GB_dir'].values,ar),
    'Prophet':sr(wf_df['Prophet_dir'].values,ar),
    'Meta-Learner':sr(wf_df['Meta_dir'].values,ar),
    '投票(3/5)':sr(wf_df['Ensemble_vote'].values,ar),
    'Meta濾網':sr(wf_df['LongBias_Meta'].values,ar),
    'Meta+LLM(舊)':sr(wf_df['LongBias_Fusion'].values,ar),
    'LLM微調':sr(wf_df['LongBias_Adjusted'].values,ar),
    '買入持有':ar,
}

cum={k:(1+pd.Series(v)).cumprod()-1 for k,v in strats.items()}

def cm(r,n):
    t=(1+pd.Series(r)).prod()-1; a=(1+t)**(252/max(len(r),1))-1
    vo=pd.Series(r).std()*np.sqrt(252); sh=a/vo if vo>0 else 0
    c=(1+pd.Series(r)).cumprod(); dd=(c/c.cummax()-1).min()
    ac=pd.Series(r)[pd.Series(r)!=0]; wr=(ac>0).mean() if len(ac)>0 else 0
    return {'策略':n,'累積':f"{t*100:.2f}%",'年化':f"{a*100:.1f}%",'波動':f"{vo*100:.1f}%",
            'Sharpe':f"{sh:.2f}",'最大回撤':f"{dd*100:.2f}%",'勝率':f"{wr*100:.1f}%"}

mdf=pd.DataFrame([cm(v,k) for k,v in strats.items()])

print("\n"+"="*85)
print("回測績效")
print("="*85)
print(mdf.to_string(index=False))
print("="*85)
mdf.to_csv(SAVE_PATH+'backtest_metrics.csv',index=False,encoding='utf-8-sig')

fig,ax=plt.subplots(figsize=(14,7))
colors=['#FF6B6B','#4ECDC4','#45B7D1','#96CEB4','#DDA0DD','#E74C3C','#AAAAAA','#FF4500','gray']
for (k,v),c in zip(cum.items(),colors):
    lw=3.0 if 'Meta濾網' in k else (2 if '持有' in k else 1.2)
    ls='--' if '濾網' in k or 'Meta-L' in k else '-'
    al=1.0 if ('Meta' in k or '持有' in k) else 0.5
    ax.plot(wf_df['Date'],v.values*100,label=k,linewidth=lw,linestyle=ls,color=c,alpha=al)
ax.axhline(0,color='black',alpha=0.3)
ax.set_title('各策略 vs 大盤 — 累積報酬率 (Stacking + Walk-Forward)',fontsize=16,fontweight='bold')
ax.set_xlabel('日期'); ax.set_ylabel('累積報酬率 (%)'); ax.legend(fontsize=9); ax.grid(True,alpha=0.3)
plt.tight_layout(); plt.savefig(SAVE_PATH+'cumulative_returns.png',dpi=150,bbox_inches='tight'); plt.show()

fig,ax=plt.subplots(figsize=(10,6))
aa={**acc,'Meta-Learner':meta_acc}
ns=list(aa.keys()); av=list(aa.values())
bars=ax.bar(ns,[a*100 for a in av],color=colors[:len(ns)],edgecolor='white')
ax.axhline(50,color='gray',linestyle='--',alpha=0.7,label='50%')
for b,a in zip(bars,av):
    ax.text(b.get_x()+b.get_width()/2,b.get_height()+0.5,f'{a*100:.1f}%',ha='center',fontweight='bold',fontsize=11)
ax.set_title('漲跌方向預測準確率',fontsize=16,fontweight='bold')
ax.set_ylabel('準確率 (%)'); ax.set_ylim(0,max(av)*100+10); ax.legend()
plt.tight_layout(); plt.savefig(SAVE_PATH+'accuracy_comparison.png',dpi=150,bbox_inches='tight'); plt.show()

fig,ax=plt.subplots(figsize=(10,8))
imp=pd.Series(last_xgb_cls.feature_importances_,index=feature_cols).sort_values(ascending=True)
imp.tail(15).plot(kind='barh',ax=ax,color=sns.color_palette("viridis",15))
ax.set_title('XGBoost — Top 15 重要特徵（含跨市場）')
plt.tight_layout(); plt.savefig(SAVE_PATH+'xgb_feature_importance.png',dpi=150,bbox_inches='tight'); plt.show()

fig,ax=plt.subplots(figsize=(8,4))
coef.sort_values().plot(kind='barh',ax=ax,color=['red' if v<0 else 'green' for v in coef.sort_values()])
ax.set_title('Stacking Meta-Learner — 各模型權重',fontsize=14,fontweight='bold')
ax.axvline(0,color='black',alpha=0.5)
plt.tight_layout(); plt.savefig(SAVE_PATH+'meta_weights.png',dpi=150,bbox_inches='tight'); plt.show()
fig, ax = plt.subplots(figsize=(14, 7))
ax.plot(wf_df['Date'], cum['Meta濾網'].values*100,
        label='Meta濾網 (純量化)', linewidth=2.5, color='#FF4500', linestyle='--')
ax.plot(wf_df['Date'], cum['Meta+LLM(舊)'].values*100,
        label='Meta+LLM (舊版直接融合)', linewidth=1.5, color='gray', alpha=0.6)
ax.plot(wf_df['Date'], cum['LLM微調'].values*100,
        label=f'LLM微調 (alpha={ALPHA})', linewidth=2.5, color='#1E90FF')
ax.plot(wf_df['Date'], cum['買入持有'].values*100,
        label='買入持有', linewidth=2, color='#AAAAAA', alpha=0.6)
ax.axhline(0, color='black', alpha=0.3)
ax.set_title('LLM 融合方式比較：直接融合 vs 機率微調', fontsize=16, fontweight='bold')
ax.set_xlabel('日期'); ax.set_ylabel('累積報酬率 (%)')
ax.legend(fontsize=10); ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig(SAVE_PATH+'llm_comparison.png', dpi=150, bbox_inches='tight')
plt.show()

# 數字比較表
print("\n"+"="*70)
print("  LLM 融合方式比較")
print("="*70)
compare = pd.DataFrame([
    cm(strats['Meta濾網'], 'Meta濾網(純量化)'),
    cm(strats['Meta+LLM(舊)'], 'Meta+LLM(舊版)'),
    cm(strats['LLM微調'], f'LLM微調(alpha={ALPHA})'),
    cm(strats['買入持有'], '買入持有'),
])
print(compare.to_string(index=False))
print("="*70)
# %%
# ============================================================
# CELL 9：預測 3/27~4/2
# ============================================================
print("[預測 3/27~4/2]")

last_price = df_clean['Close'].iloc[-1]
last_date = df_clean['Date'].iloc[-1].strftime('%Y-%m-%d')
print(f"  基準: {last_price:,.2f} ({last_date})")

# --- 各模型 T+1 預測 ---
latest_flat = last_scaler.transform(df_clean[feature_cols].tail(1).values)
latest_seq = sc_lstm.transform(df_clean[feature_cols].tail(SEQ_LENGTH).values).reshape(1,SEQ_LENGTH,len(feature_cols))

# LSTM
lstm_prob_fut = model_lstm.predict(latest_seq, verbose=0)[0][0]
lstm_dir_fut = 1 if lstm_prob_fut > LSTM_THRESHOLD else 0

# XGBoost
xgb_prob_fut = last_xgb_cls.predict_proba(latest_flat)[0][1]
xgb_ret_fut = np.clip(last_xgb_reg.predict(latest_flat)[0], -0.03, 0.03)

# RF & GB
rf_p = last_rf.predict_proba(latest_flat)[0][1]
gb_p = last_gb.predict_proba(latest_flat)[0][1]

# Prophet（5天）
pred_dates = pd.bdate_range(start='2026-03-27', periods=5, freq='B')
ppred = model_prophet.predict(pd.DataFrame({'ds': pred_dates}))
p_ratio = last_price / ppred['yhat'].values[0]
prophet_prices = ppred['yhat'].values * p_ratio

# Meta-Learner
prophet_ret_1 = prophet_prices[0]/last_price - 1
prophet_prob_fut = 1/(1+np.exp(-prophet_ret_1*100))
meta_input = np.array([[lstm_prob_fut, xgb_prob_fut, rf_p, gb_p, prophet_prob_fut]])
meta_prob_fut = meta_model.predict_proba(meta_input)[0][1]

# Regime 判斷
quant_regime = detect_regime(df_clean['Date'].iloc[-1])
meta_dir_str = '漲(持有)' if meta_prob_fut > (1-HEDGE_THRESHOLD) else '跌(避險)'

print(f"\n  [各模型看漲機率]")
print(f"    LSTM:    {lstm_prob_fut*100:.1f}% (門檻{LSTM_THRESHOLD:.2f}) -> {'漲' if lstm_dir_fut else '跌'}")
print(f"    XGBoost: {xgb_prob_fut*100:.1f}% -> {'漲' if xgb_prob_fut>0.5 else '跌'}")
print(f"    RF:      {rf_p*100:.1f}%")
print(f"    GB:      {gb_p*100:.1f}%")
print(f"    Prophet: {prophet_prob_fut*100:.1f}%")
print(f"    Meta:    {meta_prob_fut*100:.1f}% -> {meta_dir_str}")
print(f"    Regime:  {quant_regime}")

# 5天預測表
rows = []

hist_avg_up = df_clean['Target_Ret'][df_clean['Target_Ret']>0].mean()
hist_avg_down = df_clean['Target_Ret'][df_clean['Target_Ret']<0].mean()
lstm_est_ret = hist_avg_up if lstm_dir_fut == 1 else hist_avg_down

pl = last_price  # LSTM 累積
px = last_price  # XGBoost 累積

for i, d in enumerate(pred_dates):
    fade = 1 - i * 0.12
    pl = pl * (1 + lstm_est_ret * fade)

    # XGBoost：用漲跌幅逐日累積
    px = px * (1 + xgb_ret_fut * fade)

    # Prophet：已校正
    pp = prophet_prices[i]

    # 集成點位（加權平均）
    ens_price = 0.3*pl + 0.4*px + 0.3*pp

    rows.append({
        '日期': d.strftime('%m/%d(%a)'),
        'LSTM': f"{pl:,.0f} ({'漲' if lstm_dir_fut else '跌'})",
        'XGBoost': f"{px:,.0f} (漲{xgb_prob_fut*100:.0f}%)",
        'RF': f"漲{rf_p*100:.0f}%",
        'GB': f"漲{gb_p*100:.0f}%",
        'Prophet': f"{pp:,.0f}",
        '集成': f"{ens_price:,.0f}",
        'Meta': meta_dir_str,
    })

rdf = pd.DataFrame(rows)
print("\n" + "="*110)
print(f"[預測] 基準: {last_price:,.0f} | Regime: {quant_regime} | Meta: {meta_dir_str}")
print("="*110)
print(rdf.to_string(index=False))
print("="*110)

rdf.to_csv(SAVE_PATH+'competition_prediction.csv', index=False, encoding='utf-8-sig')

# --- 預測圖 ---
fig, ax = plt.subplots(figsize=(14, 7))
recent = df_clean.tail(40)
ax.plot(recent['Date'], recent['Close'], 'b-', linewidth=2, label='歷史')

ad = [df_clean['Date'].iloc[-1]] + list(pred_dates)

# LSTM 線
lp = [last_price]
p_tmp = last_price
for i in range(5):
    p_tmp = p_tmp * (1 + lstm_est_ret * (1 - i*0.12))
    lp.append(p_tmp)

# XGBoost 線
xp = [last_price]
p_tmp = last_price
for i in range(5):
    p_tmp = p_tmp * (1 + xgb_ret_fut * (1 - i*0.12))
    xp.append(p_tmp)

# Prophet 線
pp_line = [last_price] + list(prophet_prices)

# 集成線
ep = [last_price] + [0.3*lp[i+1]+0.4*xp[i+1]+0.3*pp_line[i+1] for i in range(5)]

ax.plot(ad, lp, 'ro-', label=f'LSTM ({"漲" if lstm_dir_fut else "跌"} {lstm_prob_fut*100:.0f}%)',
        linewidth=2, markersize=7)
ax.plot(ad, xp, 'gs-', label=f'XGBoost (漲{xgb_prob_fut*100:.0f}%)',
        linewidth=2, markersize=7)
ax.plot(ad, pp_line, 'm^-', label='Prophet', linewidth=2, markersize=7)
ax.plot(ad, ep, 'k--D', label='集成', linewidth=2.5, markersize=8, alpha=0.8)

ax.axvline(x=pd.Timestamp('2026-03-27'), color='red', linestyle=':', alpha=0.7)
ax.set_title(f'AI預測 (3/27~4/2) | Meta: {meta_dir_str} | Regime: {quant_regime}',
             fontsize=16, fontweight='bold')
ax.legend(fontsize=10); ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig(SAVE_PATH+'future_prediction.png', dpi=150, bbox_inches='tight')
plt.show()

# %%
# ============================================================
# CELL 10：混淆矩陣 + 儲存
# ============================================================
print("圖表...")

fig,axes=plt.subplots(3,1,figsize=(14,12),gridspec_kw={'height_ratios':[3,1,1]})
axes[0].plot(df_clean['Date'],df_clean['Close'],'b-',linewidth=1,alpha=0.8,label='收盤價')
axes[0].plot(df_clean['Date'],df_clean['SMA_20'],'orange',linewidth=1,alpha=0.7,label='SMA20')
axes[0].plot(df_clean['Date'],df_clean['SMA_60'],'green',linewidth=1,alpha=0.7,label='SMA60')
axes[0].fill_between(df_clean['Date'],df_clean['BB_Upper'],df_clean['BB_Lower'],alpha=0.1)
axes[0].set_title('台股加權指數 — 技術分析總覽',fontsize=16,fontweight='bold')
axes[0].legend(fontsize=9)
axes[1].plot(df_clean['Date'],df_clean['RSI_14'],'purple',linewidth=1)
axes[1].axhline(70,color='red',linestyle='--',alpha=0.5); axes[1].axhline(30,color='green',linestyle='--',alpha=0.5)
axes[1].set_ylabel('RSI'); axes[1].set_ylim(0,100)
axes[2].bar(df_clean['Date'],df_clean['MACD_Hist'],
            color=['red' if x>0 else 'green' for x in df_clean['MACD_Hist']],alpha=0.6,width=2)
axes[2].set_ylabel('MACD'); axes[2].set_xlabel('日期')
plt.tight_layout(); plt.savefig(SAVE_PATH+'technical_overview.png',dpi=150,bbox_inches='tight'); plt.show()

fig,axs=plt.subplots(1,5,figsize=(24,4))
for ax,(name,col) in zip(axs,[('LSTM','LSTM_dir'),('XGBoost','XGB_dir'),
    ('RF','RF_dir'),('GB','GB_dir'),('Meta-Learner','Meta_dir')]):
    cmat=confusion_matrix(wf_df['Actual_Dir'],wf_df[col])
    sns.heatmap(cmat,annot=True,fmt='d',cmap='Blues',ax=ax,
                xticklabels=['跌','漲'],yticklabels=['跌','漲'])
    ax.set_title(name); ax.set_xlabel('預測'); ax.set_ylabel('實際')
plt.suptitle('混淆矩陣 (Walk-Forward + Stacking)',fontweight='bold')
plt.tight_layout(); plt.savefig(SAVE_PATH+'confusion_matrices.png',dpi=150,bbox_inches='tight'); plt.show()

fig,ax=plt.subplots(figsize=(10,5))
hr=wf_df[wf_df['LongBias_Meta']==1]['Actual_Ret']*100
cr=wf_df[wf_df['LongBias_Meta']==0]['Actual_Ret']*100
ax.hist(hr,bins=30,alpha=0.6,label=f'持有日({len(hr)}天, 均值{hr.mean():+.2f}%)',color='green')
ax.hist(cr,bins=30,alpha=0.6,label=f'避險日({len(cr)}天, 均值{cr.mean():+.2f}%)',color='red')
ax.axvline(0,color='black',alpha=0.5)
ax.set_title('Meta濾網策略：持有日 vs 避險日報酬分布',fontsize=14,fontweight='bold')
ax.set_xlabel('日報酬率 (%)'); ax.set_ylabel('天數'); ax.legend()
plt.tight_layout(); plt.savefig(SAVE_PATH+'longbias_analysis.png',dpi=150,bbox_inches='tight'); plt.show()

print("\n儲存...")
for h,mdl in lstm_models.items():
    mdl.save(SAVE_PATH+f'model_lstm_t{h}.keras')
last_xgb_cls.save_model(SAVE_PATH+'model_xgb_cls.json')
last_xgb_reg.save_model(SAVE_PATH+'model_xgb.json')
with open(SAVE_PATH+'model_prophet.pkl','wb') as f: pickle.dump(model_prophet,f)
with open(SAVE_PATH+'extras.pkl','wb') as f:
    pickle.dump({'scaler':last_scaler,'sc_lstm':sc_lstm,'rf':last_rf,'gb':last_gb,
                 'meta_model':meta_model,'feature_cols':feature_cols,
                 'accuracies':acc,'hedge_threshold':HEDGE_THRESHOLD},f)

print(f"\n{'='*60}")
print("v5.0 完成")
print(f"{'='*60}")
for k,v in acc.items():
    print(f"  {k:12s}: {v*100:.1f}%")
print(f"  {'Meta-Learner':12s}: {meta_acc*100:.1f}%")
print(f"  Meta濾網: 持有{hp:.0f}% / 避險{100-hp:.0f}%")

# ============================================================
# CELL 11：LLM 三維度新聞情緒分析
# ============================================================
!pip install openai -q
from openai import OpenAI
import getpass, re

print("\n[LLM 多維度情緒分析]")
print("  輸入 OpenAI API Key（沒有就按 Enter 跳過）：")
api_key = getpass.getpass("API Key: ")

sentiment_score = 0.0
GPT_EXPLANATION = ""
REGIME_LLM = "Neutral"
news_titles = []

if api_key.strip():
    client = OpenAI(api_key=api_key)

    print("  抓取新聞...")

    for sym in ["2330.TW","TSM","^TWII"]:
        try:
            tk = yf.Ticker(sym)
            news = tk.news
            items = news.get('feed', news) if isinstance(news, dict) else (news if isinstance(news, list) else [])
            for item in items[:3]:
                if isinstance(item, dict):
                    t = item.get('title') or item.get('headline') or ''
                    if not t and 'content' in item: t = item['content'].get('title','')
                    if t and t not in news_titles: news_titles.append(t)
        except: pass

    for sym in ["SPY","^VIX"]:
        try:
            tk = yf.Ticker(sym)
            news = tk.news
            items = news.get('feed', news) if isinstance(news, dict) else (news if isinstance(news, list) else [])
            for item in items[:2]:
                if isinstance(item, dict):
                    t = item.get('title') or item.get('headline') or ''
                    if not t and 'content' in item: t = item['content'].get('title','')
                    if t and t not in news_titles: news_titles.append(t)
        except: pass

    if len(news_titles) < 5:
        for sym in ["NVDA","AAPL"]:
            try:
                tk = yf.Ticker(sym)
                news = tk.news
                items = news.get('feed', news) if isinstance(news, dict) else (news if isinstance(news, list) else [])
                for item in items[:2]:
                    if isinstance(item, dict):
                        t = item.get('title') or item.get('headline') or ''
                        if not t and 'content' in item: t = item['content'].get('title','')
                        if t and t not in news_titles: news_titles.append(t)
            except: pass

    if not news_titles:
        latest = df_clean.iloc[-1]
        news_titles = [
            f"TAIEX closed at {latest['Close']:,.0f}, daily change {latest['Ret_1d']*100:+.2f}%",
            f"RSI(14) = {latest['RSI_14']:.1f}",
            f"SOX previous day: {latest['SOX_Prev_Ret']*100:+.2f}%",
        ]

    news_text = "\n".join([f"{i+1}. {t}" for i, t in enumerate(news_titles[:10])])
    print(f"  共 {len(news_titles)} 則新聞")

    # 三維度情緒分析
    try:
        prompt = f"""You are a senior macro strategist at a global hedge fund.
Analyze these news headlines and provide THREE separate sentiment scores for their impact on Taiwan's TAIEX index tomorrow.

NEWS:
{news_text}

Score each dimension from -1.0 (extremely bearish) to +1.0 (extremely bullish):

1. SEMICONDUCTOR: Impact on TSMC and chip stocks (TSMC = 30%+ of TAIEX)
2. GLOBAL_MACRO: Impact from Fed policy, USD, recession risk, geopolitics
3. MARKET_SENTIMENT: Overall risk appetite, fund flows, investor mood

Also determine the current MARKET REGIME:
- Bullish: Strong uptrend, high confidence
- Neutral: Mixed signals, sideways
- Risk-off: Defensive positioning, volatility rising
- Crisis: Panic selling, extreme fear

Reply in EXACTLY this format (numbers only, no extra text):
SEMICONDUCTOR: [score]
GLOBAL_MACRO: [score]
MARKET_SENTIMENT: [score]
REGIME: [regime]"""

        resp = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role":"system","content":"You are a financial analyst. Follow the format exactly."},
                      {"role":"user","content":prompt}],
            temperature=0.3, max_tokens=100
        )
        raw = resp.choices[0].message.content.strip()
        print(f"\n  GPT 回覆:\n  {raw}")

        # 解析三維分數
        semi_score = 0.0; macro_score = 0.0; sent_score = 0.0
        for line in raw.split('\n'):
            line = line.strip()
            match = re.search(r'(-?\d+\.?\d*)', line)
            if match:
                val = float(match.group())
                val = max(-1.0, min(1.0, val))
                if 'SEMI' in line.upper():
                    semi_score = val
                elif 'MACRO' in line.upper() or 'GLOBAL' in line.upper():
                    macro_score = val
                elif 'SENTIMENT' in line.upper() or 'MARKET_S' in line.upper():
                    sent_score = val
            if 'REGIME' in line.upper():
                for r in ['Crisis','Risk-off','Bearish','Neutral','Bullish']:
                    if r.lower() in line.lower():
                        REGIME_LLM = r; break

        # 加權綜合
        sentiment_score = semi_score * 0.50 + macro_score * 0.25 + sent_score * 0.25
        sentiment_score = max(-1.0, min(1.0, sentiment_score))

        print(f"\n  [三維情緒]")
        print(f"    半導體:   {semi_score:+.2f} (權重50%)")
        print(f"    全球宏觀: {macro_score:+.2f} (權重25%)")
        print(f"    市場情緒: {sent_score:+.2f} (權重25%)")
        print(f"    加權總分: {sentiment_score:+.2f}")
        print(f"    LLM Regime: {REGIME_LLM}")

        # GPT 解釋
        exp_resp = client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[{"role":"system","content":"用繁體中文簡潔回答。"},
                      {"role":"user","content":f"你分析了新聞給出半導體{semi_score:+.1f}、宏觀{macro_score:+.1f}、情緒{sent_score:+.1f}、regime={REGIME_LLM}。新聞：\n{news_text}\n請用3~5點說明理由。"}],
            temperature=0.3, max_tokens=300
        )
        GPT_EXPLANATION = exp_resp.choices[0].message.content.strip()
        print(f"\n  [分析摘要]")
        for line in GPT_EXPLANATION.split('\n'):
            if line.strip(): print(f"    {line.strip()}")

    except Exception as e:
        print(f"  [!] GPT 失敗: {e}")
        sentiment_score = 0.0
else:
    print("  [跳過] 未輸入 Key")

if sentiment_score > 0.5: s_label = "[強多]"
elif sentiment_score > 0.1: s_label = "[偏多]"
elif sentiment_score > -0.1: s_label = "[中性]"
elif sentiment_score > -0.5: s_label = "[偏空]"
else: s_label = "[強空]"

# --- 雙引擎融合 + Regime ---
print("\n" + "="*60)
print("[雙引擎融合 + Regime 決策]")
print("="*60)

try:
    _ = meta_prob_fut
except NameError:
    meta_prob_fut = meta_prob[-1] if len(mp) > 0 else 0.5

# LLM 機率微調器
ALPHA = 0.10

# sentiment_score 已經是 [-1, 1]，直接用
Final_Prob = meta_prob_fut * (1 + ALPHA * sentiment_score)
Final_Prob = max(0.0, min(1.0, Final_Prob))  # clip

print(f"\n  量化 Meta:       {meta_prob_fut*100:.1f}%")
print(f"  LLM 情緒分數:    {sentiment_score:+.2f} {s_label}")
print(f"  調整公式:        {meta_prob_fut*100:.1f}% * (1 + {ALPHA} * {sentiment_score:+.2f})")
print(f"  調整幅度:        {(Final_Prob - meta_prob_fut)*100:+.2f}%")
print(f"  {'─'*40}")
print(f"  >>> 調整後機率:   {Final_Prob*100:.1f}%")

# Regime 修正
quant_regime = detect_regime(df_clean['Date'].iloc[-1])
combined_regime = REGIME_LLM if api_key.strip() else quant_regime

# Regime-aware 決策（跟 Cell 7 邏輯一致）
if combined_regime == 'Crisis': t = 0.40
elif combined_regime == 'Risk-off': t = 0.45
elif combined_regime == 'Bearish': t = 0.50
elif combined_regime == 'Neutral': t = 0.55
else: t = 0.60

should_hedge = Final_Prob < (1 - t)

if combined_regime in ['Crisis','Risk-off']:
    if not should_hedge:
        final_decision = "[偏多但高風險] 輕倉持有"; decision_tag = "輕倉"
    else:
        final_decision = "[避險模式] 空手觀望"; decision_tag = "避險"
elif combined_regime == 'Bearish':
    if Final_Prob >= 0.60:
        final_decision = "[逆勢偏多] 謹慎持有"; decision_tag = "偏多"
    else:
        final_decision = "[空頭確認] 建議空手"; decision_tag = "偏空"
else:
    if Final_Prob >= 0.60:
        final_decision = "[強力看多] 持有/加碼"; decision_tag = "強多"
    elif Final_Prob >= 0.50:
        final_decision = "[溫和看多] 持有"; decision_tag = "偏多"
    elif Final_Prob >= 0.40:
        final_decision = "[中性觀望] 減碼"; decision_tag = "觀望"
    else:
        final_decision = "[看空] 建議空手"; decision_tag = "偏空"

meta_dir_str = final_decision

print(f"\n  Regime: {combined_regime} (門檻{t*100:.0f}%)")
print(f"  決策:   {final_decision}")
print("="*60)

# 儲存
llm_result = {
    '日期': datetime.now().strftime('%Y-%m-%d %H:%M'),
    '情緒分數': sentiment_score,
    'Regime_LLM': REGIME_LLM,
    'Regime_Quant': quant_regime,
    '量化機率': round(meta_prob_fut*100, 1),
    '調整後機率': round(Final_Prob*100, 1),
    '綜合機率': round(Final_Prob*100, 1),
    '決策': decision_tag,
}
llm_log = SAVE_PATH + 'llm_sentiment_log.csv'
llm_df = pd.DataFrame([llm_result])
if os.path.exists(llm_log):
    existing = pd.read_csv(llm_log)
    llm_df = pd.concat([existing, llm_df], ignore_index=True)
llm_df.to_csv(llm_log, index=False, encoding='utf-8-sig')

# 摘要圖
fig, axes = plt.subplots(1, 3, figsize=(16, 4))

# 情緒儀表
ax = axes[0]
colors_g = ['#FF4444','#FF8800','#FFCC00','#88CC00','#00AA00']
bds = [-1,-0.5,-0.1,0.1,0.5,1.0]
lbls = ['強空','偏空','中性','偏多','強多']
for i in range(5):
    ax.barh(0, bds[i+1]-bds[i], left=bds[i], height=0.5, color=colors_g[i], alpha=0.3)
    ax.text((bds[i]+bds[i+1])/2, -0.4, lbls[i], ha='center', fontsize=7, color='gray')
ax.plot(sentiment_score, 0, 'k^', markersize=18)
ax.set_xlim(-1.1,1.1); ax.set_ylim(-0.6,0.5); ax.set_yticks([])
ax.set_title(f'LLM 情緒: {sentiment_score:+.2f} {s_label}', fontsize=11, fontweight='bold')

# Regime
ax = axes[1]
ax.axis('off')
regime_colors = {'Bullish':'#00AA00','Neutral':'#FFCC00','Bearish':'#FF8800','Risk-off':'#FF4444','Crisis':'#990000'}
rc = regime_colors.get(combined_regime, '#AAAAAA')
ax.text(0.5, 0.7, 'Market Regime', ha='center', fontsize=13, fontweight='bold')
ax.text(0.5, 0.35, combined_regime, ha='center', fontsize=20, fontweight='bold', color=rc)
ax.text(0.5, 0.1, f'(量化:{quant_regime} / LLM:{REGIME_LLM})', ha='center', fontsize=9, color='gray')

# 決策
ax = axes[2]
ax.axis('off')
box_c = '#d4edda' if '多' in decision_tag else '#f8d7da' if '避' in decision_tag or '空' in decision_tag else '#fff3cd'
ax.text(0.5, 0.75, '最終決策', ha='center', fontsize=13, fontweight='bold')
ax.text(0.5, 0.45, f'綜合機率: {Final_Prob*100:.1f}%', ha='center', fontsize=12)
ax.text(0.5, 0.15, final_decision, ha='center', fontsize=11, fontweight='bold',
        bbox=dict(boxstyle='round,pad=0.4', facecolor=box_c, edgecolor='gray'))

plt.tight_layout()
plt.savefig(SAVE_PATH + 'llm_sentiment.png', dpi=150, bbox_inches='tight')
plt.show()

print(f"\n[OK] 分析完成 | 圖: {SAVE_PATH}llm_sentiment.png")